export const mockData = {
	"code": 200,
	"data": {
		"id": 30,
		"project_name": "30-ceo 新建项目",
		"project_code": "2024-06-012-FW",
		"project_mode": "公开招标",
		"state": "已审批",
		"permitting_state": 1,
		"permitting_process": 1,
		"create_id": 29,
		"istop": 1,
		"main_contract_id": 14,
		"create_time": "2024-06-19 17:28",
		"main_contract": "已签约",
		"earnest_money_state": "暂无",
		"contract_party_a": "暂无",
		"contract_party_b": "暂无",
		"contract_payment_ratio": "0%",
		"contract_info": {
			"id": 14,
			"project_id": 30,
			"is_project": 1,
			"contract_code": "2024-06-012-FW",
			"contract_party_a_company_id": 4,
			"contract_party_b_company_id": 6,
			"contract_name": "ceo提交测试1",
			"contract_money": 10000,
			"type": 4,
			"tariff": 13,
			"is_main": 1,
			"is_subcontract": 1,
			"contract_pid": 0,
			"subcontract_remarks": "可以分包",
			"remarks": "ceo提交测试",
			"file": "[\"http://oa.io/storage/uploads/2024-06-15/4169b3cfc6cf6d1bac577a60c0c5f596.png\", \"http://oa.io/storage/uploads/2024-06-15/4169b3cfc6cf6d1bac577a60c0c5f596.png\"]",
			"permitting_state": 1,
			"permitting_process": 1,
			"status": 1,
			"create_id": 29,
			"create_time": 1718789381,
			"update_time": 1718789381,
			"delete_time": 0,
			"contract_party_a_company_name": "某中铁",
			"contract_party_b_company_name": "北京公司",
			"payment_sum": 0,
			"invoice_sum": 0,
			"tag": 0,
			"children": [
				{
					"id": 15,
					"project_id": 30,
					"is_project": 1,
					"contract_code": "2024-06-012-FW-001",
					"contract_party_a_company_id": 6,
					"contract_party_b_company_id": 7,
					"contract_name": "测试二级合同1",
					"contract_money": 10000,
					"type": 4,
					"tariff": 13,
					"is_main": 0,
					"is_subcontract": 1,
					"contract_pid": 14,
					"subcontract_remarks": "可以分包",
					"remarks": "ceo提交测试",
					"file": "[\"http://oa.io/storage/uploads/2024-06-15/4169b3cfc6cf6d1bac577a60c0c5f596.png\", \"http://oa.io/storage/uploads/2024-06-15/4169b3cfc6cf6d1bac577a60c0c5f596.png\"]",
					"permitting_state": 1,
					"permitting_process": 1,
					"status": 1,
					"create_id": 29,
					"create_time": 1718810935,
					"update_time": 1718810935,
					"delete_time": 0,
					"contract_party_a_company_name": "北京公司",
					"contract_party_b_company_name": "测试公司7",
					"payment_sum": 0,
					"invoice_sum": 0,
					"type_name": "劳务合同",
					"tag": 1,
					"children": [
						{
							"id": 19,
							"project_id": 30,
							"is_project": 1,
							"contract_code": "2024-06-012-FW-001-001",
							"contract_party_a_company_id": 7,
							"contract_party_b_company_id": 11,
							"contract_name": "测试三级合同1",
							"contract_money": 10000,
							"type": 4,
							"tariff": 13,
							"is_main": 0,
							"is_subcontract": 1,
							"contract_pid": 15,
							"subcontract_remarks": "可以分包",
							"remarks": "ceo提交测试",
							"file": "[\"http://oa.io/storage/uploads/2024-06-15/4169b3cfc6cf6d1bac577a60c0c5f596.png\", \"http://oa.io/storage/uploads/2024-06-15/4169b3cfc6cf6d1bac577a60c0c5f596.png\"]",
							"permitting_state": 1,
							"permitting_process": 1,
							"status": 1,
							"create_id": 29,
							"create_time": 1718814396,
							"update_time": 1719027018,
							"delete_time": 0,
							"contract_party_a_company_name": "测试公司7",
							"contract_party_b_company_name": "测试公司11",
							"payment_sum": 0,
							"invoice_sum": 0,
							"type_name": "劳务合同",
							"tag": 0,
							"children": [
								{
									"id": 22,
									"project_id": 30,
									"is_project": 1,
									"contract_code": "2024-06-012-FW-001-001-001",
									"contract_party_a_company_id": 11,
									"contract_party_b_company_id": 14,
									"contract_name": "测试四级合同1",
									"contract_money": 123,
									"type": 4,
									"tariff": 1,
									"is_main": 0,
									"is_subcontract": 1,
									"contract_pid": 19,
									"subcontract_remarks": "111",
									"remarks": "1111",
									"file": "",
									"permitting_state": 1,
									"permitting_process": 1,
									"status": 1,
									"create_id": 29,
									"create_time": 1718814446,
									"update_time": 1718970186,
									"delete_time": 0,
									"contract_party_a_company_name": "测试公司11",
									"contract_party_b_company_name": "测试公司14",
									"payment_sum": 0,
									"invoice_sum": 0,
									"type_name": "劳务合同",
									"tag": 0,
									"children": [
										{
											"id": 24,
											"project_id": 30,
											"is_project": 1,
											"contract_code": "2024-06-012-FW-001-001-001-001",
											"contract_party_a_company_id": 14,
											"contract_party_b_company_id": 16,
											"contract_name": "测试五级合同1",
											"contract_money": 10000,
											"type": 4,
											"tariff": 13,
											"is_main": 0,
											"is_subcontract": 1,
											"contract_pid": 22,
											"subcontract_remarks": "可以分包",
											"remarks": "ceo提交测试",
											"file": "[\"http://oa.io/storage/uploads/2024-06-15/4169b3cfc6cf6d1bac577a60c0c5f596.png\", \"http://oa.io/storage/uploads/2024-06-15/4169b3cfc6cf6d1bac577a60c0c5f596.png\"]",
											"permitting_state": 1,
											"permitting_process": 1,
											"status": 1,
											"create_id": 29,
											"create_time": 1718814486,
											"update_time": 1718969522,
											"delete_time": 0,
											"contract_party_a_company_name": "测试公司14",
											"contract_party_b_company_name": "测试公司16",
											"payment_sum": 0,
											"invoice_sum": 0,
											"type_name": "劳务合同",
											"tag": 0,
											"children": []
										}
									]
								},
								{
									"id": 23,
									"project_id": 30,
									"is_project": 1,
									"contract_code": "2024-06-012-FW-001-001-002",
									"contract_party_a_company_id": 11,
									"contract_party_b_company_id": 15,
									"contract_name": "测试四级合同2",
									"contract_money": 10000,
									"type": 4,
									"tariff": 13,
									"is_main": 0,
									"is_subcontract": 1,
									"contract_pid": 19,
									"subcontract_remarks": "可以分包",
									"remarks": "ceo提交测试",
									"file": "[\"http://oa.io/storage/uploads/2024-06-15/4169b3cfc6cf6d1bac577a60c0c5f596.png\", \"http://oa.io/storage/uploads/2024-06-15/4169b3cfc6cf6d1bac577a60c0c5f596.png\"]",
									"permitting_state": 1,
									"permitting_process": 1,
									"status": 1,
									"create_id": 29,
									"create_time": 1718814452,
									"update_time": 1718969611,
									"delete_time": 0,
									"contract_party_a_company_name": "测试公司11",
									"contract_party_b_company_name": "测试公司15",
									"payment_sum": 1480,
									"invoice_sum": 0,
									"type_name": "劳务合同",
									"tag": 0,
									"children": []
								}
							]
						},
						{
							"id": 20,
							"project_id": 30,
							"is_project": 1,
							"contract_code": "2024-06-012-FW-001-002",
							"contract_party_a_company_id": 7,
							"contract_party_b_company_id": 12,
							"contract_name": "测试三级合同2",
							"contract_money": 10000,
							"type": 4,
							"tariff": 13,
							"is_main": 0,
							"is_subcontract": 1,
							"contract_pid": 15,
							"subcontract_remarks": "可以分包",
							"remarks": "ceo提交测试",
							"file": "[\"http://oa.io/storage/uploads/2024-06-15/4169b3cfc6cf6d1bac577a60c0c5f596.png\", \"http://oa.io/storage/uploads/2024-06-15/4169b3cfc6cf6d1bac577a60c0c5f596.png\"]",
							"permitting_state": 1,
							"permitting_process": 1,
							"status": 1,
							"create_id": 29,
							"create_time": 1718814402,
							"update_time": 1719027011,
							"delete_time": 0,
							"contract_party_a_company_name": "测试公司7",
							"contract_party_b_company_name": "测试公司12",
							"payment_sum": 0,
							"invoice_sum": 0,
							"type_name": "劳务合同",
							"tag": 0,
							"children": []
						},
						{
							"id": 21,
							"project_id": 30,
							"is_project": 1,
							"contract_code": "2024-06-012-FW-001-003",
							"contract_party_a_company_id": 7,
							"contract_party_b_company_id": 13,
							"contract_name": "测试三级合同3",
							"contract_money": 222,
							"type": 4,
							"tariff": 1,
							"is_main": 0,
							"is_subcontract": 1,
							"contract_pid": 15,
							"subcontract_remarks": "111",
							"remarks": "111",
							"file": "",
							"permitting_state": 1,
							"permitting_process": 1,
							"status": 1,
							"create_id": 29,
							"create_time": 1718814407,
							"update_time": 1719112686,
							"delete_time": 0,
							"contract_party_a_company_name": "测试公司7",
							"contract_party_b_company_name": "测试公司13",
							"payment_sum": 123,
							"invoice_sum": 0,
							"type_name": "劳务合同",
							"tag": 0,
							"children": []
						}
					]
				},
				{
					"id": 16,
					"project_id": 30,
					"is_project": 1,
					"contract_code": "2024-06-012-FW-002",
					"contract_party_a_company_id": 6,
					"contract_party_b_company_id": 8,
					"contract_name": "测试二级合同2",
					"contract_money": 10000,
					"type": 4,
					"tariff": 13,
					"is_main": 0,
					"is_subcontract": 1,
					"contract_pid": 14,
					"subcontract_remarks": "可以分包",
					"remarks": "ceo提交测试",
					"file": "[\"http://oa.io/storage/uploads/2024-06-15/4169b3cfc6cf6d1bac577a60c0c5f596.png\", \"http://oa.io/storage/uploads/2024-06-15/4169b3cfc6cf6d1bac577a60c0c5f596.png\"]",
					"permitting_state": 1,
					"permitting_process": 1,
					"status": 1,
					"create_id": 29,
					"create_time": 1718810948,
					"update_time": 1718810949,
					"delete_time": 0,
					"contract_party_a_company_name": "北京公司",
					"contract_party_b_company_name": "测试公司8",
					"payment_sum": 0,
					"invoice_sum": 0,
					"type_name": "劳务合同",
					"tag": 0,
					"children": []
				},
				{
					"id": 17,
					"project_id": 30,
					"is_project": 1,
					"contract_code": "2024-06-012-FW-003",
					"contract_party_a_company_id": 6,
					"contract_party_b_company_id": 9,
					"contract_name": "测试二级合同3",
					"contract_money": 10000,
					"type": 4,
					"tariff": 13,
					"is_main": 0,
					"is_subcontract": 1,
					"contract_pid": 14,
					"subcontract_remarks": "可以分包",
					"remarks": "ceo提交测试",
					"file": "[\"http://oa.io/storage/uploads/2024-06-15/4169b3cfc6cf6d1bac577a60c0c5f596.png\", \"http://oa.io/storage/uploads/2024-06-15/4169b3cfc6cf6d1bac577a60c0c5f596.png\"]",
					"permitting_state": 1,
					"permitting_process": 1,
					"status": 1,
					"create_id": 29,
					"create_time": 1718810954,
					"update_time": 1719025040,
					"delete_time": 0,
					"contract_party_a_company_name": "北京公司",
					"contract_party_b_company_name": "测试公司9",
					"payment_sum": 0,
					"invoice_sum": 0,
					"type_name": "劳务合同",
					"tag": 0,
					"children": []
				},
				{
					"id": 18,
					"project_id": 30,
					"is_project": 1,
					"contract_code": "2024-06-012-FW-004",
					"contract_party_a_company_id": 6,
					"contract_party_b_company_id": 10,
					"contract_name": "测试二级合同4",
					"contract_money": 10000,
					"type": 4,
					"tariff": 13,
					"is_main": 0,
					"is_subcontract": 1,
					"contract_pid": 14,
					"subcontract_remarks": "可以分包",
					"remarks": "ceo提交测试",
					"file": "[\"http://oa.io/storage/uploads/2024-06-15/4169b3cfc6cf6d1bac577a60c0c5f596.png\", \"http://oa.io/storage/uploads/2024-06-15/4169b3cfc6cf6d1bac577a60c0c5f596.png\"]",
					"permitting_state": 1,
					"permitting_process": 1,
					"status": 1,
					"create_id": 29,
					"create_time": 1718810960,
					"update_time": 1719117761,
					"delete_time": 0,
					"contract_party_a_company_name": "北京公司",
					"contract_party_b_company_name": "测试公司10",
					"payment_sum": 0,
					"invoice_sum": 0,
					"type_name": "劳务合同",
					"tag": 0,
					"children": []
				}
			]
		},
		"group_company_list": [
			{
				"id": 4,
				"name": "某中铁",
				"cash_money": 0,
				"issuing_invoice_sum": 0,
				"receiving_invoice_sum": 0,
				"contract_payment_sum": 0,
				"contract_revenue_sum": 0
			},
			{
				"id": 7,
				"name": "测试公司7",
				"cash_money": 0,
				"issuing_invoice_sum": 0,
				"receiving_invoice_sum": 0,
				"contract_payment_sum": 0,
				"contract_revenue_sum": 0
			},
			{
				"id": 8,
				"name": "测试公司8",
				"cash_money": 0,
				"issuing_invoice_sum": 0,
				"receiving_invoice_sum": 0,
				"contract_payment_sum": 0,
				"contract_revenue_sum": 0
			},
			{
				"id": 9,
				"name": "测试公司9",
				"cash_money": 0,
				"issuing_invoice_sum": 0,
				"receiving_invoice_sum": 0,
				"contract_payment_sum": 0,
				"contract_revenue_sum": 0
			},
			{
				"id": 10,
				"name": "测试公司10",
				"cash_money": 0,
				"issuing_invoice_sum": 0,
				"receiving_invoice_sum": 0,
				"contract_payment_sum": 0,
				"contract_revenue_sum": 0
			},
			{
				"id": 11,
				"name": "测试公司11",
				"cash_money": 0,
				"issuing_invoice_sum": 0,
				"receiving_invoice_sum": 0,
				"contract_payment_sum": 0,
				"contract_revenue_sum": 0
			},
			{
				"id": 12,
				"name": "测试公司12",
				"cash_money": 0,
				"issuing_invoice_sum": 0,
				"receiving_invoice_sum": 0,
				"contract_payment_sum": 0,
				"contract_revenue_sum": 0
			},
			{
				"id": 13,
				"name": "测试公司13",
				"cash_money": 0,
				"issuing_invoice_sum": 0,
				"receiving_invoice_sum": 0,
				"contract_payment_sum": 0,
				"contract_revenue_sum": 0
			},
			{
				"id": 14,
				"name": "测试公司14",
				"cash_money": 0,
				"issuing_invoice_sum": 0,
				"receiving_invoice_sum": 0,
				"contract_payment_sum": 0,
				"contract_revenue_sum": 0
			},
			{
				"id": 15,
				"name": "测试公司15",
				"cash_money": 0,
				"issuing_invoice_sum": 0,
				"receiving_invoice_sum": 0,
				"contract_payment_sum": 0,
				"contract_revenue_sum": 0
			},
			{
				"id": 16,
				"name": "测试公司16",
				"cash_money": 0,
				"issuing_invoice_sum": 0,
				"receiving_invoice_sum": 0,
				"contract_payment_sum": 0,
				"contract_revenue_sum": 0
			}
		],
		"partners_company_list": [
			{
				"id": 6,
				"name": "北京公司",
				"cash_money": 0,
				"issuing_invoice_sum": 0,
				"receiving_invoice_sum": 0,
				"contract_payment_sum": 160300,
				"contract_revenue_sum": 0
			}
		]
	},
	"msg": "获取成功"
}